org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=false
org.gradle.caching=true

minecraft_version=1.21.10
minecraft_version_range=[1.21.10]
java_version=21

fabric_loader_version=0.19.2
fabric_api_version=0.138.4+1.21.10
neo_version=21.10.64
neo_version_range=[21.10.64,)
loader_version_range=[4,)

mod_id=shared_lootr
mod_name=Shared Lootr
mod_license=GPL-3.0-or-later
mod_version=1.3.1+1.21.10
mod_group_id=dev.rinchan.sharedlootr
mod_authors=RinChan
mod_description=One shared inventory and one opened state for every Lootr container.

rinlib_version=0.2.0+1.21.10
lootr_version=1.18.32.99
lootr_fabric_version=tBqlJU85
lootr_neoforge_version=72pESX4q
fabric_cloth_config_version=20.0.149
jade_fabric_version=nCbsPtPw
jade_neoforge_version=q7P6JKIH
