org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=false
org.gradle.caching=true

minecraft_version=1.21.11
minecraft_version_range=[1.21.11]
java_version=21

fabric_loader_version=0.19.2
fabric_api_version=0.141.6+1.21.11
neo_version=21.11.45
neo_version_range=[21.11.45,)
loader_version_range=[4,)

mod_id=shared_lootr
mod_name=Shared Lootr
mod_license=GPL-3.0-or-later
mod_version=1.3.2+1.21.11
mod_group_id=dev.rinchan.sharedlootr
mod_authors=RinChan
mod_description=One shared inventory and one opened state for every Lootr container.

rinlib_version=0.2.0+1.21.11
lootr_version=1.20.34.104
lootr_fabric_version=efKMR8nl
lootr_neoforge_version=TBkxTN54
fabric_cloth_config_version=21.11.153
jade_fabric_version=swJhAyak
jade_neoforge_version=LDFqgwEA
