plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${rootProject.mod_id}-neoforge"
}

sourceSets.main.java.srcDir rootProject.file('shared/src/main/java')
sourceSets.main.resources.srcDir rootProject.file('shared/src/main/resources')
sourceSets.main.resources.srcDir tasks.register('generateModMetadata', ProcessResources) {
    def replaceProperties = [
        minecraft_version_range: rootProject.minecraft_version_range,
        neo_version_range      : rootProject.neo_version_range,
        loader_version_range   : rootProject.loader_version_range,
        lootr_version          : rootProject.lootr_version,
        mod_id                 : rootProject.mod_id,
        mod_name               : rootProject.mod_name,
        mod_license            : rootProject.mod_license,
        mod_version            : rootProject.mod_version,
        mod_authors            : rootProject.mod_authors,
        mod_description        : rootProject.mod_description
    ]
    inputs.properties replaceProperties
    filteringCharset = 'UTF-8'
    expand replaceProperties
    from 'src/main/templates'
    into layout.buildDirectory.dir('generated/sources/modMetadata')
}

neoForge {
    version = rootProject.neo_version
    mods {
        "${rootProject.mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
    runs {
        client { client() }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'sharedLootr.smoke', System.getProperty('sharedLootr.smoke', 'false')
        }
        configureEach {
            logLevel = org.slf4j.event.Level.INFO
        }
    }
}

neoForge.ideSyncTask tasks.named('generateModMetadata')

dependencies {
    implementation "maven.modrinth:lootr:${rootProject.lootr_neoforge_version}"
    implementation "dev.rinchan:rinlib-neoforge:${rootProject.rinlib_version}"
    compileOnly "maven.modrinth:jade:${rootProject.jade_neoforge_version}"
    runtimeOnly "maven.modrinth:jade:${rootProject.jade_neoforge_version}"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${rootProject.mod_id}-neoforge"
            from components.java
        }
    }
}
