org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=false
org.gradle.caching=true

minecraft_version=1.21.4
minecraft_version_range=[1.21.4]
java_version=21

fabric_loader_version=0.19.2
fabric_api_version=0.119.4+1.21.4
neo_version=21.4.157
neo_version_range=[21.4.157,)
loader_version_range=[4,)

mod_id=shared_lootr
mod_name=Shared Lootr
mod_license=GPL-3.0-or-later
mod_version=1.3.2+1.21.4
mod_group_id=dev.rinchan.sharedlootr
mod_authors=RinChan
mod_description=One shared inventory and one opened state for every Lootr container.

rinlib_version=0.2.0+1.21.4
lootr_version=1.13.36.89
lootr_fabric_version=HmnhGIXV
lootr_neoforge_version=Z0vjfoTl
fabric_cloth_config_version=17.0.144
jade_fabric_version=sSHUBFoq
jade_neoforge_version=Rpe14jmy
