org.gradle.jvmargs=-Xmx2g
org.gradle.parallel=false
org.gradle.caching=true

minecraft_version=1.21
minecraft_version_range=[1.21]
java_version=21

fabric_loader_version=0.19.2
fabric_api_version=0.102.0+1.21
neo_version=21.0.167
neo_version_range=[21.0.167,)
loader_version_range=[4,)

mod_id=shared_lootr
mod_name=Shared Lootr
mod_license=GPL-3.0-or-later
mod_version=1.3.0+1.21
mod_group_id=dev.rinchan.sharedlootr
mod_authors=RinChan
mod_description=One shared inventory and one opened state for every Lootr container.

rinlib_version=0.2.0+1.21
lootr_version=1.10.35.99
lootr_fabric_version=cOrO8AXN
lootr_neoforge_version=q5IlMBVM
fabric_cloth_config_version=15.0.140
jade_fabric_version=VQc9njMw
jade_neoforge_version=eNY0Rg8n
