plugins {
    id 'java-library'
    id 'maven-publish'
    id 'fabric-loom'
}

def root = rootProject

def modId = root.property('mod_id')

base {
    archivesName = "${modId}-fabric"
}

sourceSets.main.java.setSrcDirs([root.file('shared/src/main/java'), file('src/main/java')])
sourceSets.main.resources.setSrcDirs([root.file('shared/src/main/resources'), file('src/main/resources')])

dependencies {
    minecraft "com.mojang:minecraft:${root.property('minecraft_version')}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${root.property('fabric_loader_version')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${root.property('fabric_api_version')}"
    modImplementation "maven.modrinth:lootr:${root.property('lootr_fabric_version')}"
    modImplementation "dev.rinchan:rinlib-fabric:${root.property('rinlib_version')}"
    modCompileOnly "maven.modrinth:jade:${root.property('jade_fabric_version')}"
    modRuntimeOnly "maven.modrinth:jade:${root.property('jade_fabric_version')}"
    modCompileOnly "me.shedaniel.cloth:cloth-config-fabric:${root.property('fabric_cloth_config_version')}"
    modLocalRuntime "me.shedaniel.cloth:cloth-config-fabric:${root.property('fabric_cloth_config_version')}"
}

def resourceProperties = [
    mod_id: modId,
    mod_name: root.property('mod_name'),
    mod_version: root.property('mod_version'),
    mod_license: root.property('mod_license'),
    mod_authors: root.property('mod_authors'),
    mod_description: root.property('mod_description'),
    minecraft_version: root.property('minecraft_version'),
    fabric_loader_version: root.property('fabric_loader_version'),
    lootr_version: root.property('lootr_version'),
    rinlib_version: root.property('rinlib_version')
]

processResources {
    inputs.properties(resourceProperties)
    filesMatching('fabric.mod.json') {
        expand resourceProperties
    }
}

loom {
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = "${modId}-fabric"
            from components.java
        }
    }
}
