org.gradle.daemon=false
org.gradle.jvmargs=-Xmx2g
org.gradle.workers.max=1
minecraft_version=1.20.1
forge_version=47.4.10
fabric_loader_version=0.15.11
fabric_api_version=0.92.2+1.20.1
cloth_config_version=2xQdCMyG
jade_forge_version=xJQHCmWJ
jade_fabric_version=ahavHbAT
lootr_forge_version=mWTXC1ZX
lootr_fabric_version=nj1zDLc6
rinlib_version=0.2.0+1.20.1
mod_id=shared_lootr
mod_name=Shared Lootr
