plugins {
    id 'net.neoforged.moddev' version '2.0.141' apply false
    id 'net.fabricmc.fabric-loom' version '1.15-SNAPSHOT' apply false
}

subprojects {
    group = rootProject.mod_group_id
    version = rootProject.mod_version

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://api.modrinth.com/maven' }
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases' }
    }

    plugins.withType(JavaPlugin).configureEach {
        java.toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version as int)
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
        }
    }
}
